// The cream knockout mark (generated by scripts/gen-logo.mjs). Rendered on the
// dark background per the brief — never the dark-on-dark original.

export function Logo({ size = 30, className }: { size?: number; className?: string }) {
  return (
    <img
      src="/nexus-mark.png"
      width={size}
      height={size}
      alt="Nexus"
      className={className}
      style={{ display: "block", objectFit: "contain" }}
    />
  );
}
